spring:
  application:
    name: techup-backend
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      credentials:
        access-key: 1
        secret-key: 2
      s3:
        bucket: ogh-spring-prac
      region:
        static: ${AWS_REGION}
jwtData:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
server:
  port: 8080



