spring:
  application:
    name: techup-backend
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      credentials:
        access-key: 1
        secret-key: 2
      s3:
        bucket: ogh-spring-prac
      region:
        static: ${AWS_REGION}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: cb439249a99e424ac915855adda81547
#            client-secret: ogb7Se9dSg0IDiN4xs0QJtPRRUqGcUAG
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
#              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwtData:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
server:
  port: 8080

portone:
  secret: ${PORTONE_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


