spring:
  application:
    name: techup-backend

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDR}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
#              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwtData:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
server:
  port: 8080

portone:
  secret: ${PORTONE_SECRET}
  store-id: ${PORTONE_STOREID}
  channel-key: ${PORTONE_CHANNEL_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

kafka:
  enabled: false

management:
  endpoints:
    web:
    exposure:
      include: 'health'
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
