spring:
  application:
    name: techup-backend
  data:
    redis:
      host: 192.0.40.206
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDR}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
        #              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwtData:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

portone:
  secret: ${PORTONE_SECRET}
  store-id: ${PORTONE_STOREID}
  channel-key: ${PORTONE_CHANNEL_KEY}

logging:
  level:
    com.example.backend: TRACE
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    db:
      enabled: true
    mail:
      enabled: false
    diskspace:
      enabled: false
    ping:
      enabled: false
    ssl:
      enabled: false

kafka:
   enabled: false

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: qwer1234
    key-store-type: PKCS12
    key-alias: springboot
